namespace PTRON.Identity;

public sealed record Pais(string Codigo, string Nome);

/// <summary>ISO 3166-1 countries in Portuguese for the sign-up form. Brazil comes first, the rest is alphabetical.</summary>
public static class Paises
{
    public static IReadOnlyList<Pais> Todos { get; } = new Pais[]
    {
        new("BR", "Brasil"),
        new("AF", "Afeganistão"),
        new("ZA", "África do Sul"),
        new("AL", "Albânia"),
        new("DE", "Alemanha"),
        new("AD", "Andorra"),
        new("AO", "Angola"),
        new("AI", "Anguilla"),
        new("AQ", "Antártida"),
        new("AG", "Antígua e Barbuda"),
        new("SA", "Arábia Saudita"),
        new("DZ", "Argélia"),
        new("AR", "Argentina"),
        new("AM", "Armênia"),
        new("AW", "Aruba"),
        new("AU", "Austrália"),
        new("AT", "Áustria"),
        new("AZ", "Azerbaijão"),
        new("BS", "Bahamas"),
        new("BH", "Bahrein"),
        new("BD", "Bangladesh"),
        new("BB", "Barbados"),
        new("BE", "Bélgica"),
        new("BZ", "Belize"),
        new("BJ", "Benin"),
        new("BM", "Bermudas"),
        new("BY", "Bielorrússia"),
        new("BO", "Bolívia"),
        new("BQ", "Bonaire, Santo Eustáquio e Saba"),
        new("BA", "Bósnia e Herzegovina"),
        new("BW", "Botsuana"),
        new("BN", "Brunei"),
        new("BG", "Bulgária"),
        new("BF", "Burkina Faso"),
        new("BI", "Burundi"),
        new("BT", "Butão"),
        new("CV", "Cabo Verde"),
        new("CM", "Camarões"),
        new("KH", "Camboja"),
        new("CA", "Canadá"),
        new("QA", "Catar"),
        new("KZ", "Cazaquistão"),
        new("TD", "Chade"),
        new("CL", "Chile"),
        new("CN", "China"),
        new("CY", "Chipre"),
        new("SG", "Cingapura"),
        new("CO", "Colômbia"),
        new("KM", "Comores"),
        new("CG", "Congo"),
        new("CD", "Congo (República Democrática do)"),
        new("KP", "Coreia do Norte"),
        new("KR", "Coreia do Sul"),
        new("CI", "Costa do Marfim"),
        new("CR", "Costa Rica"),
        new("HR", "Croácia"),
        new("CU", "Cuba"),
        new("CW", "Curaçao"),
        new("DK", "Dinamarca"),
        new("DJ", "Djibuti"),
        new("DM", "Dominica"),
        new("EG", "Egito"),
        new("SV", "El Salvador"),
        new("AE", "Emirados Árabes Unidos"),
        new("EC", "Equador"),
        new("ER", "Eritreia"),
        new("SK", "Eslováquia"),
        new("SI", "Eslovênia"),
        new("ES", "Espanha"),
        new("SZ", "Essuatíni"),
        new("US", "Estados Unidos"),
        new("EE", "Estônia"),
        new("ET", "Etiópia"),
        new("FJ", "Fiji"),
        new("PH", "Filipinas"),
        new("FI", "Finlândia"),
        new("FR", "França"),
        new("GA", "Gabão"),
        new("GM", "Gâmbia"),
        new("GH", "Gana"),
        new("GE", "Geórgia"),
        new("GI", "Gibraltar"),
        new("GD", "Granada"),
        new("GR", "Grécia"),
        new("GL", "Groenlândia"),
        new("GP", "Guadalupe"),
        new("GU", "Guam"),
        new("GT", "Guatemala"),
        new("GG", "Guernsey"),
        new("GY", "Guiana"),
        new("GF", "Guiana Francesa"),
        new("GN", "Guiné"),
        new("GQ", "Guiné Equatorial"),
        new("GW", "Guiné-Bissau"),
        new("HT", "Haiti"),
        new("HN", "Honduras"),
        new("HK", "Hong Kong"),
        new("HU", "Hungria"),
        new("YE", "Iêmen"),
        new("BV", "Ilha Bouvet"),
        new("CX", "Ilha Christmas"),
        new("IM", "Ilha de Man"),
        new("NF", "Ilha Norfolk"),
        new("AX", "Ilhas Åland"),
        new("KY", "Ilhas Cayman"),
        new("CC", "Ilhas Cocos (Keeling)"),
        new("CK", "Ilhas Cook"),
        new("FO", "Ilhas Faroe"),
        new("GS", "Ilhas Geórgia do Sul e Sandwich do Sul"),
        new("HM", "Ilhas Heard e McDonald"),
        new("FK", "Ilhas Malvinas"),
        new("MP", "Ilhas Marianas do Norte"),
        new("MH", "Ilhas Marshall"),
        new("UM", "Ilhas Menores Distantes dos Estados Unidos"),
        new("PN", "Ilhas Pitcairn"),
        new("SB", "Ilhas Salomão"),
        new("TC", "Ilhas Turks e Caicos"),
        new("VI", "Ilhas Virgens Americanas"),
        new("VG", "Ilhas Virgens Britânicas"),
        new("IN", "Índia"),
        new("ID", "Indonésia"),
        new("IR", "Irã"),
        new("IQ", "Iraque"),
        new("IE", "Irlanda"),
        new("IS", "Islândia"),
        new("IL", "Israel"),
        new("IT", "Itália"),
        new("JM", "Jamaica"),
        new("JP", "Japão"),
        new("JE", "Jersey"),
        new("JO", "Jordânia"),
        new("KI", "Kiribati"),
        new("KW", "Kuwait"),
        new("LA", "Laos"),
        new("LS", "Lesoto"),
        new("LV", "Letônia"),
        new("LB", "Líbano"),
        new("LR", "Libéria"),
        new("LY", "Líbia"),
        new("LI", "Liechtenstein"),
        new("LT", "Lituânia"),
        new("LU", "Luxemburgo"),
        new("MO", "Macau"),
        new("MK", "Macedônia do Norte"),
        new("MG", "Madagascar"),
        new("MY", "Malásia"),
        new("MW", "Malawi"),
        new("MV", "Maldivas"),
        new("ML", "Mali"),
        new("MT", "Malta"),
        new("MA", "Marrocos"),
        new("MQ", "Martinica"),
        new("MU", "Maurício"),
        new("MR", "Mauritânia"),
        new("YT", "Mayotte"),
        new("MX", "México"),
        new("MM", "Mianmar"),
        new("FM", "Micronésia"),
        new("MZ", "Moçambique"),
        new("MD", "Moldávia"),
        new("MC", "Mônaco"),
        new("MN", "Mongólia"),
        new("ME", "Montenegro"),
        new("MS", "Montserrat"),
        new("NA", "Namíbia"),
        new("NR", "Nauru"),
        new("NP", "Nepal"),
        new("NI", "Nicarágua"),
        new("NE", "Níger"),
        new("NG", "Nigéria"),
        new("NU", "Niue"),
        new("NO", "Noruega"),
        new("NC", "Nova Caledônia"),
        new("NZ", "Nova Zelândia"),
        new("OM", "Omã"),
        new("NL", "Países Baixos"),
        new("PW", "Palau"),
        new("PS", "Palestina"),
        new("PA", "Panamá"),
        new("PG", "Papua-Nova Guiné"),
        new("PK", "Paquistão"),
        new("PY", "Paraguai"),
        new("PE", "Peru"),
        new("PF", "Polinésia Francesa"),
        new("PL", "Polônia"),
        new("PR", "Porto Rico"),
        new("PT", "Portugal"),
        new("KE", "Quênia"),
        new("KG", "Quirguistão"),
        new("GB", "Reino Unido"),
        new("CF", "República Centro-Africana"),
        new("DO", "República Dominicana"),
        new("CZ", "República Tcheca"),
        new("RE", "Reunião"),
        new("RO", "Romênia"),
        new("RW", "Ruanda"),
        new("RU", "Rússia"),
        new("EH", "Saara Ocidental"),
        new("WS", "Samoa"),
        new("AS", "Samoa Americana"),
        new("SM", "San Marino"),
        new("SH", "Santa Helena"),
        new("LC", "Santa Lúcia"),
        new("BL", "São Bartolomeu"),
        new("KN", "São Cristóvão e Nevis"),
        new("MF", "São Martinho (França)"),
        new("SX", "São Martinho (Países Baixos)"),
        new("PM", "São Pedro e Miquelon"),
        new("ST", "São Tomé e Príncipe"),
        new("VC", "São Vicente e Granadinas"),
        new("SC", "Seicheles"),
        new("SN", "Senegal"),
        new("SL", "Serra Leoa"),
        new("RS", "Sérvia"),
        new("SY", "Síria"),
        new("SO", "Somália"),
        new("LK", "Sri Lanka"),
        new("SD", "Sudão"),
        new("SS", "Sudão do Sul"),
        new("SE", "Suécia"),
        new("CH", "Suíça"),
        new("SR", "Suriname"),
        new("SJ", "Svalbard e Jan Mayen"),
        new("TJ", "Tadjiquistão"),
        new("TH", "Tailândia"),
        new("TW", "Taiwan"),
        new("TZ", "Tanzânia"),
        new("IO", "Território Britânico do Oceano Índico"),
        new("TF", "Territórios Franceses do Sul"),
        new("TL", "Timor-Leste"),
        new("TG", "Togo"),
        new("TK", "Tokelau"),
        new("TO", "Tonga"),
        new("TT", "Trinidad e Tobago"),
        new("TN", "Tunísia"),
        new("TM", "Turcomenistão"),
        new("TR", "Turquia"),
        new("TV", "Tuvalu"),
        new("UA", "Ucrânia"),
        new("UG", "Uganda"),
        new("UY", "Uruguai"),
        new("UZ", "Uzbequistão"),
        new("VU", "Vanuatu"),
        new("VA", "Vaticano"),
        new("VE", "Venezuela"),
        new("VN", "Vietnã"),
        new("WF", "Wallis e Futuna"),
        new("ZM", "Zâmbia"),
        new("ZW", "Zimbábue"),
    };

    private static readonly Dictionary<string, Pais> ByCode =
        Todos.ToDictionary(p => p.Codigo, StringComparer.OrdinalIgnoreCase);

    public static bool IsValid(string? codigo) => !string.IsNullOrWhiteSpace(codigo) && ByCode.ContainsKey(codigo.Trim());

    public static string? Nome(string? codigo)
        => !string.IsNullOrWhiteSpace(codigo) && ByCode.TryGetValue(codigo.Trim(), out var pais) ? pais.Nome : null;
}
