// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTRON.Data;

#nullable disable

namespace PTRON.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721015845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("PTRON.Models.EntradaEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EntradasEstoque");
                });

            modelBuilder.Entity("PTRON.Models.EntradaEstoqueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaEstoqueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Qtd")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntradaEstoqueId");

                    b.HasIndex("InsumoId");

                    b.ToTable("EntradaEstoqueItens");
                });

            modelBuilder.Entity("PTRON.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("PTRON.Models.EquipamentoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Qtd")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("InsumoId");

                    b.ToTable("EquipamentoInsumos");
                });

            modelBuilder.Entity("PTRON.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Potencia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoInsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Voltagem")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoInsumoId");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("PTRON.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoAdicional")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PTRON.Models.ProdutoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Qtd")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoInsumos");
                });

            modelBuilder.Entity("PTRON.Models.TipoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposInsumo");
                });

            modelBuilder.Entity("PTRON.Models.EntradaEstoqueItem", b =>
                {
                    b.HasOne("PTRON.Models.EntradaEstoque", "EntradaEstoque")
                        .WithMany("Itens")
                        .HasForeignKey("EntradaEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTRON.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntradaEstoque");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("PTRON.Models.EquipamentoInsumo", b =>
                {
                    b.HasOne("PTRON.Models.Equipamento", "Equipamento")
                        .WithMany("Insumos")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTRON.Models.Insumo", "Insumo")
                        .WithMany("EquipamentoInsumos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("PTRON.Models.Insumo", b =>
                {
                    b.HasOne("PTRON.Models.TipoInsumo", "TipoInsumo")
                        .WithMany("Insumos")
                        .HasForeignKey("TipoInsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoInsumo");
                });

            modelBuilder.Entity("PTRON.Models.Produto", b =>
                {
                    b.HasOne("PTRON.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("PTRON.Models.ProdutoInsumo", b =>
                {
                    b.HasOne("PTRON.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTRON.Models.Produto", "Produto")
                        .WithMany("Insumos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PTRON.Models.EntradaEstoque", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PTRON.Models.Equipamento", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("PTRON.Models.Insumo", b =>
                {
                    b.Navigation("EquipamentoInsumos");
                });

            modelBuilder.Entity("PTRON.Models.Produto", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("PTRON.Models.TipoInsumo", b =>
                {
                    b.Navigation("Insumos");
                });
#pragma warning restore 612, 618
        }
    }
}
